accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

articles/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    CommentGet,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleCreateView,
)

urlpatterns = [
    path("", ArticleListView.as_view(), name="article_list"),
    path("<int:pk>", CommentGet.as_view(), name="article_detail"),
    path("<int:pk>/edit", ArticleUpdateView.as_view(), name="article_update"),
    path(
        "<int:pk>/delete",
        ArticleDeleteView.as_view(),
        name="article_delete"
    ),
    path("new/", ArticleCreateView.as_view(), name="article_create"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('articles/', include('articles.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        )

    class Meta:
        app_label = "articles"

    def __str__(self):
        short = f'{self.title[:20]} ..'
        return f'{short if len(self.title) >= 20 else self.title} ' \
               f'| by {self.author}'

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})

    @property
    def shortened_body(self):
        shortened = self.body[:200]
        return shortened if len(self.body) > 200 else f'{shortened} ..'


class Comment(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        )
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        shortened = self.text[:100]
        return shortened if len(self.text) < 100 else f'{shortened} ..'

    def get_absolute_url(self):
        return reverse("article_list")

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )


class CustomUserChangeForm(UserChangeForm):
    model = CustomUser
    fields = (
        "username",
        "email",
        "age",
    )

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

articles/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, FormView
from django.views.generic.edit import UpdateView, DeleteView
from django.views import View
from django.views.generic.detail import SingleObjectMixin

from .models import Article
from .froms import CommentForm


TEMP_PATH = 'articles/'


class ArticleListView(ListView):
    model = Article
    template_name = f"{TEMP_PATH}/article_list.html"

    ordering = ['-date']


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = f"{TEMP_PATH}/article_create.html"
    fields = (
        "title",
        "body",
    )

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentGet(DetailView):  # new
    model = Article
    template_name = f"{TEMP_PATH}article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):  # new
    model = Article
    form_class = CommentForm
    template_name = f"{TEMP_PATH}article_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.get_object()
        return reverse("article_detail", kwargs={"pk": article.pk})


class ArticleDetailView(LoginRequiredMixin, View):  # new
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = (
        "title",
        "body",
    )
    template_name = f"{TEMP_PATH}/article_update.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = f"{TEMP_PATH}/article_delete.html"
    success_url = reverse_lazy("article_list")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomePageView(TemplateView):
    template_name = "home.html"

templates/articles/article_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>New Article</h1>
    <form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <p>Writting Author: {{ user }}</p>
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>

{% endblock content %}

templates/articles/article_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Article</h1>
    <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ article.title }}"?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>

{% endblock content %}

templates/articles/article_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Article Detail</h1>
    <div class="article-entry">
        <h2>{{ object.title }}</h2>
        <p>by {{ object.author }} | {{ object.date }}</p>
        <p>{{ object.body }}</p>
    </div>

    <p><a href="{% url 'article_update' article.pk %}">Edit</a> |
    <a href="{% url 'article_delete' article.pk %}">Delete</a></p>
    <p>Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>

    <hr>
    <h2>Comments</h2>

     {% for comment in article.comment_set.all %}
        <div class="card">
            <div class="card-header">
                <span style="float:left;" class="font-weight-bold">{{ comment.author }}</span>
                <span style="float:right;" class="text-muted">{{ comment.date }}</span>
            </div>
            <div class="card-body">
               {{ comment.text }}
            </div>
            <div class="card-footer text-muted" style="float:right;">
                <a href="#">React</a>
            </div>
        </div>
         <br/>
    {% endfor %}
    <h2>Add a comment</h2>
        <form action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success ml-2" type="submit">Save</button>
        </form>

{% endblock content %}

templates/articles/article_list.html
{% extends "base.html" %}

{% block title %}Articles{%  endblock title %}

{% block content %}
<div>
    <h1>Articles</h1>
    <a href="{%  url 'article_create' %}" class="nav-link px-2 link-dark"> + New Article</a><br/>
    {% for article in article_list %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold">{{ article.title }}</span> &middot;
                <span class="text-muted">by {{ article.author }} | {{ article.date }}</span>
            </div>
            <div class="card-body">
               {{ article.shortened_body }}
            </div>
            <div class="card-footer text-left text-muted">
                <a href="{% url 'article_detail' article.pk %}">Read</a> |
                <a href="{% url 'article_update' article.pk %}">Edit</a> |
                <a href="{% url 'article_delete' article.pk %}">Delete</a>
                <span style="float:right;">
                    Comments: {{ article.comment_set.all|length }}
                </span>
            </div>
        </div>
<br />
{% endfor %}
{% endblock content %}

templates/articles/article_update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Edit Article</h1>
    <form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>>{% block title %}Newspaper App{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <header class="p-3 mb-3 border-bottom">
          <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
                <a href="{%  url 'article_list' %}" class="nav-link px-2 link-dark">Articles</a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% if user.is_authenticated %}
                </ul>
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
    id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}
                    </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                    </ul>
                </div>
                {% else %}
            </ul>
             <div class="text-end">
               <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
               <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
              </div>
                {% endif %}

                </div>
            </div>
        </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>

    <!-- Bootstrap JavaScript Bundle -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        Hi {{ user.username }}! You are {{ user.age }} years old now.
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a> |
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
{% endblock content %}